name: Menu
version: '${project.version}'
main: tech.secretgarden.menu.Menu
api-version: '1.20'
authors: [ ChuckLingBao ]
description: Guide to Secret Garden
depend: [TAB]
commands:
  menu:
    description: Your guide to Secret Garden
